### ISSUE TITLE
Composer install error PHP < 7.4

### ISSUE THREAD

**Issue by jaynoe** [clickpress/contao-clickskeks#1]
**Error:**
`An error occurred while executing the "contao:install-web-dir" command: PHP  
   Parse error:  syntax error, unexpected 'string' (T_STRING), expecting func  
  tion (T_FUNCTION) or const (T_CONST) in /var/www/messingwerk.de/content/ven  
  dor/clickpress/contao-clickskeks/src/EventListener/ContaoClickskeksListener  
  .php on line 37`

**Mögliche Fehlerbehebung:**
Die typed properties wurden erst in PHP 7.4 eingeführt. Entweder die Requirements bzgl PHP auf >= 7.4 setzen oder die typed properties rausnehmen?

**Comment by stefansl** [comment]
Danke! Fixed in https://github.com/clickpress/contao-clickskeks/commit/7de37e29fc9a85ad1a5ba94a10ef4a0a5fd053cd
